# Generated by Django 4.1.1 on 2022-09-16 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Categoria', max_length=20)),
                ('descripcion', models.TextField(default='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(default='Calle', max_length=30)),
                ('numero', models.IntegerField(default=1)),
                ('comuna', models.CharField(default='Comuna', max_length=30)),
                ('ciudad', models.CharField(default='Ciudad', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(default='00-00-000')),
                ('descuento', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.BigIntegerField(default=3513897259)),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SuperMarket.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Proveedor', max_length=30)),
                ('telefono', models.BigIntegerField(default=1)),
                ('web', models.URLField(default='google.com')),
                ('direccion', models.ManyToManyField(default=1, to='SuperMarket.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre', max_length=20)),
                ('precio', models.IntegerField(default=1)),
                ('stock', models.IntegerField(default=1)),
                ('Cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SuperMarket.categoria')),
                ('Prov', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SuperMarket.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ManyToManyField(default=1, to='SuperMarket.direccion'),
        ),
    ]
