# Generated by Django 4.1.1 on 2022-09-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperMarket', '0002_detalle_cat_detalle_prod_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle',
            name='Cat',
        ),
        migrations.AddField(
            model_name='detalle',
            name='Venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SuperMarket.venta'),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='telefono',
            field=models.CharField(default='3513897259', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='Fecha',
            field=models.DateField(default='2022-09-06'),
        ),
    ]
