# Generated by Django 4.1.1 on 2022-09-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SuperMarket', '0003_remove_detalle_cat_detalle_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SuperMarket.cliente'),
        ),
    ]
